### PR TITLE
fix: rollup build transformer bug

### PR DESCRIPTION
**Pull request by noname0310**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

`rollup-plugin-ts` and `rollup-plugin-typescript2` has transformer bug So I modified it to use `@rollup/plugin-typescript`.

It is a change that must be applied. The rollup build is going wrong now.

### CODE REVIEW

**Comment by ZLY201** [comment]
> It is a change that must be applied. The rollup build is going wrong now.

Can you describe it in detail?

**Comment by noname0310** [comment]
> > It is a change that must be applied. The rollup build is going wrong now.
> 
> Can you describe it in detail?

https://github.com/GoogleFeud/ts-macros/issues/23

I checked that ts-macros was not working properly in the rollup build and found that this was a bug caused by rollup plugin.

There was a problem that the code disappeared because the transformer did not work properly in the rollup build, and this was solved.

**Comment by ZLY201** [comment]
Thanks!

But I have a question, how can we avoid the problem like this which happen in production mode?

All the test we have is running in devlopment mode.

The only way I can think of is adding new unit tests but that is a unnecessary work because we have so enough tests to promiss the correctness of code.

**Comment by noname0310** [comment]
I think it's certain to run the test after build it.
However, we have to test all the builds, so the amount of tests will be quite large.
(It's also incredible that there's a test for three browsers and three versions of node js)

**Comment by ZLY201** [comment]
I'll merge this PR first.

Please see https://github.com/js-sdsl/js-sdsl/discussions/86.

We should find a good way to solve it.

**Comment by ZLY201** [comment]
> (It's also incredible that there's a test for three browsers and three versions of node js)

Thanks to karma and mocha. Good testing framework.

**Pull request merged**
