### PR TITLE
test: migrate jest to mocha

### PR DESCRIPTION
**Pull request by ZLY201**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: migrate jest to mocha

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `main` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Make tests stronger and add browser tests.

### CODE REVIEW

**Comment by ZLY201** [comment]
This proves that mocha is much more efficient than jest.

**Comment by noname0310** [comment]
Wouldn't it be more convenient to use jest Puppeter for the browser test?

**Comment by ZLY201** [comment]
> Wouldn't it be more convenient to use jest Puppeter for the browser test?

But I see this must write new test files.

**Comment by ZLY201** [comment]
This PR will not merge to version `4.1.5-beta.0`.

**Pull request merged**
