### PR TITLE
chore: upgrade browserslist

### PR DESCRIPTION
**Pull request by ZLY201**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Build-related changes
- [x] Other, please describe: upgrade browserslist

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `main` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by noname0310** [comment]
Do you have any plans to upgrade the ESM build to ES6? ES5 needs more polyfill, so building with ES6 will reduce the build size more.

**Comment by ZLY201** [comment]
> Do you have any plans to upgrade the ESM build to ES6? ES5 needs more polyfill, so building with ES6 will reduce the build size more.

Is there any good way to do research on browser compatibility for ES6?

**Comment by noname0310** [comment]
> > Do you have any plans to upgrade the ESM build to ES6? ES5 needs more polyfill, so building with ES6 will reduce the build size more.
> 
> Is there any good way to do research on browser compatibility for ES6?

https://caniuse.com/?search=es6
Please refer to this site

**Comment by ZLY201** [comment]
But we have the target to compatible with the following browser versions:

```bash
edge 12
firefox 18
chrome 49
safari 10
opera 36
node 6

```

**Comment by noname0310** [comment]
I see. I can't help it

**Comment by ZLY201** [comment]
Run firefox 18.0 test failed.

https://github.com/js-sdsl/js-sdsl/actions/runs/3279851856/jobs/5399903934

Because mocha.js has ES6 arrow function but firefox 18.0 not support.

**Comment by ZLY201** [comment]
Successful run in firefox 31!

https://github.com/js-sdsl/js-sdsl/actions/runs/3281412236/jobs/5403384090

**Comment by ZLY201** [comment]
Although we can't test some browser in specific version such as chrome 49 but I think firefox 31 is old enough.

https://mozilla.org/en-US/firefox/31.0/releasenotes/

Firefox 31 is released in July 22, 2014 even earlier than chrome 49 (2016-03-02).

https://chrome.softwaredownload.co.in/chrome-49-0-2623

We even test it in difference os including windows, ubuntu and macos.

**Pull request merged**
