### PR TITLE
refactor: add _ perfix for private and protected member

### PR DESCRIPTION
**Pull request by ZLY201**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Code style update
- [x] Refactor
- [x] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `main` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

All exported members are not expected to be inherited so `protected/private` name can be converted to improve performance and reduce packing size.

### CODE REVIEW

**Comment by noname0310** [comment]
It is already becoming a mangling for the private members by the Transformers.
Is this commit for mangling the protected member?

Then, actually, there is also a way to do Mangling for protected members without changing the code style.
But in order to do this, there's no `ts-ignore` or `as any` in the code
So I couldn't apply this optimization.

**Comment by ZLY201** [comment]
> But in order to do this, there's no ts-ignore or as any in the code

Since TS has no friend class so I must use `ts-ignore` to visit private member.

It looks like increasing perfix is the only possible solution?

**Comment by noname0310** [comment]
> > But in order to do this, there's no ts-ignore or as any in the code
> 
> Since TS has no friend class so I must use `ts-ignore` to visit private member.
> 
> It looks like add perfix is the only possible solution?

Change the field to public and use @internal

The member with @internal is omitted from d.ts, so the user cannot see it

**Comment by ZLY201** [comment]
> Change the field to public and use @internal.

This seems to invalidate private...

**Comment by ZLY201** [comment]
Is there any problem with adding the prefix?

I just want to make it more spec-compliant.

**Review by noname0310 — DISMISSED** [review]
`minify-privates-transformer` is no longer required.
But it won't make a difference if you don't remove it.

**Comment by ZLY201** [comment]
> `minify-privates-transformer` is no longer required. But it won't make a difference if you don't remove it.

I removed it, please check.

**Review by noname0310 — APPROVED** [review]
reviewed

**Pull request merged**
