### PR TITLE
ci: optimize ci

### PR DESCRIPTION
**Pull request by ZLY201**

### CODE REVIEW

**Comment by ZLY201** [comment]
https://github.com/rossjrw/pr-preview-action/issues/3

https://github.com/preactjs/compressed-size-action/issues/2

It seems there are not a good way to solve this problem.

**Comment by ZLY201** [comment]
This PR do something as follow:

- For pr preview action, I change it to only trigger in main branch.
- For compressed size action, there are no good way to fix it, so I just change it back. All of the things is good except it can't comment to PR. But there seems has a replacement?
See 
https://github.com/preactjs/compressed-size-action/issues/2
https://github.com/kuldeepkeshwar/size-plugin-bot
https://github.com/luwes/rollup-plugin-size
@noname0310 try to use the `rollup-size-plugin` next time.
- I optimize the workflow. Only when related files changed the workflow triggered and will be canceled when new commit pushed.
- I add a new step to `deploy` action to save the current documentation page in `gh-pages/previous/v${version}` when push `main` branch everytime.

@noname0310 Please to help to check all the change is good.

**Review by noname0310 — APPROVED** [review]
I will apply `rollup-plugin-size` in the next PR

**Comment by ZLY201** [comment]
> I will apply `rollup-plugin-size` in the next PR

Thanks! If succeed don't forget to remove the `compressed-size-action`.

**Pull request merged**
