### PR TITLE
build: publish@4.3.0

### PR DESCRIPTION
**Pull request by ZLY201**
Publish version 4.3.0.

Expected to be released at 01.20.

**note: The last commit must be build: publish@{version}.**

### CODE REVIEW

**Comment by ZLY201** [comment]
`dev` branch locked.

**Review by noname0310 — APPROVED** [review]
Thank you for your efforts.

**Comment by ZLY201** [comment]
Oh, I forgot that I turned on the two-factor authentication on npm. Two-factor authentication can't be disabled because it is enforced on your npm account. I will see how to solve this problem next week.

This time I have to release it manually.

**Comment by noname0310** [comment]
https://github.com/marketplace/actions/npm-otp-publish

I'm looking at a solution like this. If possible, I will revise the ci.

**Pull request merged**
